set DEFAULT_DESTINATION_DRIVE=F
set DEFAULT_SOURCE_DIRECTORY=%userprofile%

if exist "profile" (
	cd profile
    set /p DESTINATION_DRIVE=<DESTINATION_DRIVE.txt
    set /p SOURCE_DIRECTORY=<SOURCE_DIRECTORY.txt
    cd ..
    ) ELSE (
    set /p DESTINATION_DRIVE=%DEFAULT_DESTINATION_DRIVE%
    set /p SOURCE_DIRECTORY=%DEFAULT_SOURCE_DIRECTORY%
)

if [%DESTINATION_DRIVE%]==[] (
    set DESTINATION_DRIVE=%DEFAULT_DESTINATION_DRIVE%
)

if [%SOURCE_DIRECTORY%]==[] (
    set SOURCE_DIRECTORY=%DEFAULT_SOURCE_DIRECTORY%
)

echo %DESTINATION_DRIVE%
echo %SOURCE_DIRECTORY%

pause